export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'

export const LOAD_USER_INFO_REQUEST = 'LOAD_USER_INFO_REQUEST'
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS'
export const LOAD_USER_INFO_ERROR = 'LOAD_USER_INFO_ERROR'