export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'

export const LOAD_USER_INFO_REQUEST = 'LOAD_USER_INFO_REQUEST'
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS'
export const LOAD_USER_INFO_ERROR = 'LOAD_USER_INFO_ERROR'

/** 收缩页面左半部分 */
export const TOOGLE_COLLAPSE = 'TOOGLE_COLLAPSE'

/** 获取医生列表 */
export const GET_DOCTOR_REQUEST = 'GET_DOCTOR_REQUEST'
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS'
export const GET_DOCTOR_ERROR = 'GET_DOCTOR_ERROR'

/** 获取病区列表 */
export const GET_WARDS_REQUEST = 'GET_WARDS_REQUEST'
export const GET_WARDS_SUCCESS = 'GET_WARDS_SUCCESS'
export const GET_WARDS_ERROR = 'GET_WARDS_ERROR'

/** 获取患者列表 */
export const GET_PATIENT_LIST_REQUEST = 'GET_PATIENT_LIST_REQUEST'
export const GET_PATIENT_LIST_SUCCESS = 'GET_PATIENT_LIST_SUCCESS'
export const GET_PATIENT_LIST_ERROR = 'GET_PATIENT_LIST_ERROR'

/** 获取表单配置 */
export const GET_FORM_CONFIG_REQUEST = 'GET_FORM_CONFIG_REQUEST'
export const GET_FORM_CONFIG_SUCCESS = 'GET_FORM_CONFIG_SUCCESS'
export const GET_FORM_CONFIG_ERROR = 'GET_FORM_CONFIG_ERROR'

/** 保存表单数据 */
export const SAVE_FORM_DATA_REQUEST = 'SAVE_FORM_DATA_REQUEST'
export const SAVE_FORM_DATA_SUCCESS = 'SAVE_FORM_DATA_SUCCESS'
export const SAVE_FORM_DATA_ERROR = 'SAVE_FORM_DATA_ERROR'

/** 获取表单数据 */
export const GET_FORM_DATA_REQUEST = 'GET_FORM_DATA_REQUEST'
export const GET_FORM_DATA_SUCCESS = 'GET_FORM_DATA_SUCCESS'
export const GET_FORM_DATA_ERROR = 'GET_FORM_DATA_ERROR'

/** 清除获取到的表单数据 */
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA'

/** 保存术前小结部分 */
export const SAVE_PRE_OP_SUMMARY_REQUEST = 'SAVE_PRE_OP_SUMMARY_REQUEST'
export const SAVE_PRE_OP_SUMMARY_SUCCESS = 'SAVE_PRE_OP_SUMMARY_SUCCESS'
export const SAVE_PRE_OP_SUMMARY_ERROR = 'SAVE_PRE_OP_SUMMARY_ERROR'

/** 获取输血模型推荐 */
export const GET_TRANS_RECOMMEND_REQUEST = 'GET_TRANS_RECOMMEND_REQUEST'
export const GET_TRANS_RECOMMEND_SUCCESS = 'GET_TRANS_RECOMMEND_SUCCESS'
export const GET_TRANS_RECOMMEND_ERROR = 'GET_TRANS_RECOMMEND_ERROR'

/** 获取表单数据 -术前 */
export const GET_PRE_OP_FORM_DATA_REQUEST = 'GET_PRE_OP_FORM_DATA_REQUEST'
export const GET_PRE_OP_FORM_DATA_SUCCESS = 'GET_PRE_OP_FORM_DATA_SUCCESS'
export const GET_PRE_OP_FORM_DATA_ERROR = 'GET_PRE_OP_FORM_DATA_ERROR'

/** 获取表单数据-术中 */
export const GET_INOP_FORM_DATA_REQUEST = 'GET_INOP_FORM_DATA_REQUEST'
export const GET_INOP_FORM_DATA_SUCCESS = 'GET_INOP_FORM_DATA_SUCCESS'
export const GET_INOP_FORM_DATA_ERROR = 'GET_INOP_FORM_DATA_ERROR'

/** 获取表单数据-术中 */
export const GET_POST_OP_FORM_DATA_REQUEST = 'GET_POST_OP_FORM_DATA_REQUEST'
export const GET_POST_OP_FORM_DATA_SUCCESS = 'GET_POST_OP_FORM_DATA_SUCCESS'
export const GET_POST_OP_FORM_DATA_ERROR = 'GET_POST_OP_FORM_DATA_ERROR'
/** 获取拟施手术风险数据 */
export const GET_OP_RISK_DATA_REQUEST = 'GET_OP_RISK_DATA_REQUEST'
export const GET_OP_RISK_DATA_SUCCESS = 'GET_OP_RISK_DATA_SUCCESS'
export const GET_OP_RISK_DATA_ERROR = 'GET_OP_RISK_DATA_ERROR'

/** 清除拟施手术风险数据 */
export const CLEAR_OP_RISK_DATA = 'CLEAR_OP_RISK_DATA'

/** real time predict */
export const REALTIME_PREDICT_REQUEST = 'REALTIME_PREDICT_REQUEST'
export const REALTIME_PREDICT_SUCCESS = 'REALTIME_PREDICT_SUCCESS'
export const REALTIME_PREDICT_ERROR = 'REALTIME_PREDICT_ERROR'

/** 获取全局配置 */
export const LOAD_CONFIG_REQUEST = 'LOAD_CONFIG_REQUEST'
export const LOAD_CONFIG_SUCCESS = 'LOAD_CONFIG_SUCCESS'
export const LOAD_CONFIG_ERROR = 'LOAD_CONFIG_ERROR'

/** 清空患者列表 */
export const CLEAR_PATIENTLIST_DATA = 'CLEAR_PATIENTLIST_DATA'

/** 同步患者列表 page */
export const SYNC_PATIENTLIST_PAGE = 'SYNC_PATIENTLIST_PAGE'

/** 记录患者列表当前 scrollTop */
export const SYNC_PATIENTLIST_SCROLL_TOP = 'SYNC_PATIENTLIST_SCROLL_TOP'

/** 修改术前小结状态为编辑 -- 只用于后端记录状态 */
export const CHANGE_PREOP_SUMMARY_STATUS_TO_EDIT_REQUEST = 'CHANGE_PREOP_SUMMARY_STATUS_TO_EDIT_REQUEST'
export const CHANGE_PREOP_SUMMARY_STATUS_TO_EDIT_SUCCESS = 'CHANGE_PREOP_SUMMARY_STATUS_TO_EDIT_SUCCESS'
export const CHANGE_PREOP_SUMMARY_STATUS_TO_EDIT_ERROR = 'CHANGE_PREOP_SUMMARY_STATUS_TO_EDIT_ERROR'

/** 获取术后小结记录数据 */
export const LOAD_POST_OP_SUMMARY_RECORD_REQUEST = 'LOAD_POST_OP_SUMMARY_RECORD_REQUEST'
export const LOAD_POST_OP_SUMMARY_RECORD_SUCCESS = 'LOAD_POST_OP_SUMMARY_RECORD_SUCCESS'
export const LOAD_POST_OP_SUMMARY_RECORD_ERROR = 'LOAD_POST_OP_SUMMARY_RECORD_ERROR'

/** 保存术后小结记录 */
export const SAVE_POST_OP_SUMMARY_RECORD_REQUEST = 'SAVE_POST_OP_SUMMARY_RECORD_REQUEST'
export const SAVE_POST_OP_SUMMARY_RECORD_SUCCESS = 'SAVE_POST_OP_SUMMARY_RECORD_SUCCESS'
export const SAVE_POST_OP_SUMMARY_RECORD_ERROR = 'SAVE_POST_OP_SUMMARY_RECORD_ERROR'

/** 保存术后小结记录 */
export const DELETE_POST_OP_SUMMARY_RECORD_REQUEST = 'DELETE_POST_OP_SUMMARY_RECORD_REQUEST'
export const DELETE_POST_OP_SUMMARY_RECORD_SUCCESS = 'DELETE_POST_OP_SUMMARY_RECORD_SUCCESS'
export const DELETE_POST_OP_SUMMARY_RECORD_ERROR = 'DELETE_POST_OP_SUMMARY_RECORD_ERROR'
